name: Hello WF
on: 
  workflow_dispatch:

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    environment: tes
    steps:
    - run: echo "Approved"

    
  hello-one:
    runs-on: ubuntu-latest
    needs: manual-approval
    environment: test
    steps:
    - run: echo "Hello One"
